### ISSUE TITLE
Sticky.js:387 Uncaught TypeError: Cannot read property 'scrollTop' of null

### ISSUE THREAD

**Issue by evgenosiptsov** [yahoo/react-stickynode#45] opened 2016-06-22 20:13 UTC
Hi!
![screenshot 2016-06-22 23 08 10](https://cloud.githubusercontent.com/assets/17506504/16281895/0b03eb48-38cf-11e6-81f9-1fb0c0aee405.png)
![screenshot 2016-06-22 23 11 14](https://cloud.githubusercontent.com/assets/17506504/16281899/0fe643f4-38cf-11e6-854a-a5d880e96269.png)

Because document.windows.body is NULL in chrome - http://cl.ly/3g233n0I0q04

**Comment by evgenosiptsov** [comment] 2016-06-22 20:16
You should use somesing else 
http://stackoverflow.com/questions/9916747/why-is-document-body-null-in-my-javascript

**Comment by src-code** [comment] 2016-06-28 19:17
@evgenosiptsov The code is referencing `document.body`, not `document.window.body` so not sure why body would be null for you.  I'm unable to reproduce when running the functional tests.

**Comment by evgenosiptsov** [comment] 2016-07-02 19:59
Yes, you right, it's my mistake in description. All the matter document.body is null in Chrome

**Comment by hankhsiao** [comment] 2016-07-15 15:25
It almost becomes a standard to put your script with async or below the
body, because it will block rendering without doing any. Previously, many
JS libraries will listen to onLoad event and then initialize their
component, but it will take user much longer to use it.

In other words, if you don't have particular requirement, I strongly
recommend you to do either one approach. Here is a better explanation on
this topic.

http://stackoverflow.com/questions/436411/where-is-the-best-place-to-put-script-tags-in-html-markup

**Comment by src-code** [comment] 2016-07-15 22:28
While what @hankhsiao said is true, I think it's also true that there's no good reason for these globals to be defined outside of `componentDidMount()` (I suppose it was done to ensure they'd only be initialized once per page load and shared for all instances of the component, but we can do that from within (`componentDidMount()` too.)  I'd suggest we move them into that function, and that should resolve any problems related to where or how a user decides to execute this script.

**Comment by src-code** [comment] 2016-07-15 23:07
Fixed in PR #48

**Closed by src-code** 2016-07-15 23:07 UTC
